Repository nanoframework/nanoFramework.SignalR.Client, pull requests merged in 2022-02, with the labels that each got.

#15 Fix State after a failed reconnect or connect
  nanoFramework.SignalR.Client/HubConnection.cs
Labels: Type: bug, Type: enhancement

#16 Websocket Connect added try catch
  nanoFramework.SignalR.Client/HubConnection.cs
Labels: Type: bug

#21 Removed nanoFramework.Windows.Storage.Streams
  nanoFramework.SignalR.Client.nuspec
  nanoFramework.SignalR.Client/nanoFramework.SignalR.Client.nfproj
  nanoFramework.SignalR.Client/packages.config
Labels: Area: Config-and-Build, Type: dependencies
